/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Complejo {
    private var real: Int=0
    private var imag: Int=0
    fun inicializar(real:Int, imag:Int){
        this.real=real
        this.imag=imag
    }
    fun mostrar(){
        println("(${real}, ${imag})")
    }
    override fun toString() : String {
        return " (${real}, ${imag})"

    }
}
    
    

fun main() {
    var complejo: Complejo
    complejo = Complejo()
    complejo.inicializar(3,4)
    complejo.mostrar()
    println(" Mi numero complejo es ${complejo.toString()}")

}

